"""
Django settings for agentpro project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os 
from  decouple import config
from datetime import timedelta
LOG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'logs')

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

from celery.schedules import crontab

# Beat schedule (will be stored in database)
CELERY_BEAT_SCHEDULE = {
    'mark-inactive-agents-every-minute': {
        'task': 'BaseApp.tasks.mark_inactive_agents',
        'schedule': crontab(minute='*/1'),  # Every minute
        'options': {
            'expires': 300,  # Task expires after 5 minutes if not executed
        },
    },
}
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# Timezone
CELERY_TIMEZONE = 'Asia/Kolkata'
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY='django-insecure-!8g1fuxx5po9fh5gf8d0=w4x752iw_j%!4f'#qb60#jpi!oby60

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE= True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
USE_TLS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'daphne',
    'channels',
    'oauth2_provider',
    'django_celery_beat',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'BaseApp.apps.BaseappConfig',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

#  ========================================
# MONITORING CONFIGURATION SETTINGS
# ========================================
# ───────────────────────────────────────
# Common Configuration
# ───────────────────────────────────────
COMMON_MONITORING_THRESHOLDS = {
    "INFO": 40.0,
    "WARNING": 60.0,
    "CRITICAL": 80.0,
}

COMMON_ALERT_SETTINGS = {
    "ALERT_CONTINUOUS_MINUTES": 5, 
    "ALERT_CACHE_TTL": 3600, 
}

# ───────────────────────────────────────
# CPU Monitoring Configuration
# ───────────────────────────────────────
CPU_MONITORING_CONFIG = {
    "THRESHOLDS": COMMON_MONITORING_THRESHOLDS.copy(),
    "ALERT_CONTINUOUS_MINUTES": COMMON_ALERT_SETTINGS["ALERT_CONTINUOUS_MINUTES"],
    "ALERT_CACHE_TTL": COMMON_ALERT_SETTINGS["ALERT_CACHE_TTL"],
    "CACHE_KEY_PREFIX": "cpu_util_alert",
}

# Backward compatibility - Keep these for existing code that may use them
CPU_UTILIZATION_THRESHOLDS = CPU_MONITORING_CONFIG["THRESHOLDS"]
CPU_ALERT_CONTINUOUS_MINUTES = CPU_MONITORING_CONFIG["ALERT_CONTINUOUS_MINUTES"]
CPU_ALERT_CACHE_TTL = CPU_MONITORING_CONFIG["ALERT_CACHE_TTL"]

# ───────────────────────────────────────
# Memory Monitoring Configuration
# ───────────────────────────────────────
MEMORY_MONITORING_CONFIG = {
    "THRESHOLDS": COMMON_MONITORING_THRESHOLDS.copy(),
    "ALERT_CONTINUOUS_MINUTES": COMMON_ALERT_SETTINGS["ALERT_CONTINUOUS_MINUTES"],
    "ALERT_CACHE_TTL": COMMON_ALERT_SETTINGS["ALERT_CACHE_TTL"],
    "CACHE_KEY_PREFIX": "memory_util_alert",
}

# Backward compatibility
MEMORY_UTILIZATION_THRESHOLDS = MEMORY_MONITORING_CONFIG["THRESHOLDS"]
MEMORY_ALERT_CONTINUOUS_MINUTES = MEMORY_MONITORING_CONFIG["ALERT_CONTINUOUS_MINUTES"]
MEMORY_ALERT_CACHE_TTL = MEMORY_MONITORING_CONFIG["ALERT_CACHE_TTL"]

# ───────────────────────────────────────
# Network Monitoring Configuration
# ───────────────────────────────────────
NETWORK_MONITORING_CONFIG = {
    "THRESHOLDS": COMMON_MONITORING_THRESHOLDS.copy(),
    "ALERT_CONTINUOUS_MINUTES": COMMON_ALERT_SETTINGS["ALERT_CONTINUOUS_MINUTES"],
    "ALERT_CACHE_TTL": COMMON_ALERT_SETTINGS["ALERT_CACHE_TTL"],
    "CACHE_KEY_PREFIX": "network_util_alert",
}

# Backward compatibility
NETWORK_UTILIZATION_THRESHOLDS = NETWORK_MONITORING_CONFIG["THRESHOLDS"]

# ───────────────────────────────────────
# Disk Monitoring Configuration
# ───────────────────────────────────────
DISK_MONITORING_CONFIG = {
    "THRESHOLDS": COMMON_MONITORING_THRESHOLDS.copy(),
    "ALERT_CONTINUOUS_MINUTES": COMMON_ALERT_SETTINGS["ALERT_CONTINUOUS_MINUTES"],
    "ALERT_CACHE_TTL": COMMON_ALERT_SETTINGS["ALERT_CACHE_TTL"],
    "CACHE_KEY_PREFIX": "disk_util_alert",
    # Disk-specific settings
    "BULK_INSERT_CHUNK_SIZE": 500,
    "PARTITION_VERIFICATION_TIMEOUT": 86400,  # 24 hours in seconds
    "PARTITION_VERIFICATION_CACHE_PREFIX": "partition_verification_sent",
}

# Backward compatibility for disk service (supports both naming conventions)
DISK_MONITORING_CONFIG["ALERT_STREAK_MINUTES"] = DISK_MONITORING_CONFIG["ALERT_CONTINUOUS_MINUTES"]

# ───────────────────────────────────────
# Alert Service Configuration
# ───────────────────────────────────────
ALERT_SERVICE_CONFIG = {
    "THRESHOLDS": COMMON_MONITORING_THRESHOLDS.copy(),
    "THROTTLE_MINUTES": COMMON_ALERT_SETTINGS["ALERT_CONTINUOUS_MINUTES"],
    "CACHE_TTL": COMMON_ALERT_SETTINGS["ALERT_CACHE_TTL"],
    "CACHE_HEALTH_THRESHOLD": 1000,
    # Alert type mapping
    "TYPE_MAPPING": {
        "cpu": "CPU Usage",
        "memory": "Memory Usage",
        "disk": "Disk Usage",
        "network": "Port Usage",
    }
}


WEBSOCKET_CONFIG = {
    'EVENT_COOLDOWN_SECONDS': 60,
    'MAX_QUEUE_SIZE': 1000,
    'BATCH_PROCESSING_SIZE': 5,
    'PROCESSING_TIMEOUT': 30.0,
    'QUEUE_GET_TIMEOUT': 5.0,
    'SLOW_PROCESSING_THRESHOLD': 5.0,
    'COOLDOWN_CACHE_MAX_SIZE': 100,
    'COOLDOWN_CACHE_CLEANUP_MULTIPLIER': 2,
}

EVENT_SERVICE_CONFIG = {
    # Cache and deduplication settings
    'EVENT_CACHE_TIMEOUT': 60,
    'MAX_DESCRIPTION_LENGTH': 500,
    
    # Rate limiting settings
    'RATE_LIMIT_WINDOW': 60,
    'MIN_EVENT_INTERVAL': 1,
    
    # Performance settings
    'SLOW_OPERATION_THRESHOLD': 1.0,
    'MAX_EVENTS_LIMIT': 100,
    'CLEANUP_BATCH_SIZE': 1000,
    
    # Maintenance settings
    'DEFAULT_CLEANUP_DAYS': 30,
}
UNKNOWN_ENTITIES_CONFIG = {
    "MAX_UNKNOWN_KEYS": 1000,        
    "UNKNOWN_EXPIRY_SECONDS": 300, 
}

MONITORING_HANDLER_CONFIG = {
    # Existing configurations
    "MAX_CONCURRENT_SERVICES": 7,    
    "DEVICE_CACHE_TTL": 3600,
    
    "MAX_DEVICE_CACHE_SIZE": 200,         
    "SLOW_PROCESSING_THRESHOLD": 5.0,     
    "SERVICE_TIMEOUT": 30.0,              
    "PARALLEL_PROCESSING_TIMEOUT": 60.0,   
    "CACHE_CLEANUP_INTERVAL": 100,    
}

# ==========================================================================================


#  Helper function to get list from environment
def get_list_from_env(env_var, default=None):
    value = os.environ.get(env_var, default or '')
    return [item.strip() for item in value.split(',') if item.strip()]

# Get values
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'
HOST_IP = os.environ.get('HOST_IP', 'localhost,192.168.100.91')
# SECRET_KEY = os.environ.get('SECRET_KEY')
# Get lists from comma-separated environment variables
ALLOWED_HOSTS = get_list_from_env('ALLOWED_HOSTS', '192.168.100.91,localhost,127.0.0.1,0.0.0.0,backend')

CORS_ALLOWED_ORIGINS = get_list_from_env('CORS_ALLOWED_ORIGINS', 
    'https://localhost,http://localhost:3000,https://127.0.0.1,httpS://192.168.100.91')

CSRF_TRUSTED_ORIGINS = get_list_from_env('CSRF_TRUSTED_ORIGINS',
    'https://localhost,https://127.0.0.1')

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# settings.py
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
}

OAUTH2_PROVIDER_APPLICATION_MODEL= 'oauth2_provider.Application'

ROOT_URLCONF = 'CentralServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'agent_monitoring.log'),
            'formatter': 'verbose',
            'maxBytes': 512000,    # Approx. 1000 log entries (~500 KB)
            'backupCount': 1,      # No backups
        },
    },
    'loggers': {
        'agent_monitoring': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


OAUTH2_PROVIDER_APPLICATION_MODEL= 'oauth2_provider.Application'

ROOT_URLCONF = 'CentralServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [('redis', 6379)], 
        },
    },
}

WSGI_APPLICATION = 'CentralServer.wsgi.application'
ASGI_APPLICATION = 'CentralServer.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER'), 
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'


USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# If you have app-specific static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DISK_STATS_CONFIG = {
    'CACHE_TIMEOUT': {
        'hourly': 300,     # 5 minutes
        'daily': 3600,     # 1 hour
        'weekly': 21600,   # 6 hours  
        'monthly': 86400,  # 24 hours
        'custom': 600      # 10 minutes
    },
    'MAX_RANGE_DAYS': 730,           # 2 years max
    'SLOW_QUERY_THRESHOLD': 5.0,     # 5 seconds
    'MAX_FAILURES': 5,               # Circuit breaker threshold
    'CIRCUIT_BREAKER_TIMEOUT': 300,  # 5 minutes
    'ENABLE_QUERY_LOGGING': True,
    'ENABLE_PERFORMANCE_MONITORING': True,
}
 
CPU_STATS_CONFIG = {
    'CACHE_TIMEOUT': {
        'hourly': 300,     # 5 minutes
        'daily': 3600,     # 1 hour
        'weekly': 21600,   # 6 hours  
        'monthly': 86400,  # 24 hours
        'custom': 600      # 10 minutes
    },
    'MAX_RANGE_DAYS': 730,           # 2 years max
    'SLOW_QUERY_THRESHOLD': 5.0,     # 5 seconds
    'MAX_FAILURES': 5,               # Circuit breaker threshold
    'CIRCUIT_BREAKER_TIMEOUT': 300,  # 5 minutes
    'ENABLE_QUERY_LOGGING': True,
    'ENABLE_PERFORMANCE_MONITORING': True,
}
 
MEMORY_STATS_CONFIG = {
    'CACHE_TIMEOUT': {
        'hourly': 300,     # 5 minutes
        'daily': 3600,     # 1 hour
        'weekly': 21600,   # 6 hours  
        'monthly': 86400,  # 24 hours
        'custom': 600      # 10 minutes
    },
    'MAX_RANGE_DAYS': 730,           # 2 years max
    'SLOW_QUERY_THRESHOLD': 5.0,     # 5 seconds
    'MAX_FAILURES': 5,               # Circuit breaker threshold
    'CIRCUIT_BREAKER_TIMEOUT': 300,  # 5 minutes
    'ENABLE_QUERY_LOGGING': True,
    'ENABLE_PERFORMANCE_MONITORING': True,
}