from django.contrib import admin
from .models.models import *
from .models.roles import *

admin.site.register(Agent)
admin.site.register(Device)
admin.site.register(CPU)
admin.site.register(GPU)
admin.site.register(Memory)
admin.site.register(Storage)
admin.site.register(Partition)
admin.site.register(NIC)
admin.site.register(Port)
admin.site.register(IPAddress)
admin.site.register(Event)
admin.site.register(MonitoringCheckpoint)
admin.site.register(CpuMonitoring)
admin.site.register(MemoryMonitoring)
admin.site.register(DiskMonitoring)
admin.site.register(PartitionMonitoring)
admin.site.register(NetworkPortMonitoring)
admin.site.register(Alert)
admin.site.register(WebUser)
admin.site.register(PendingDeletion)
admin.site.register(MonitoringSession)
admin.site.register(Group)
admin.site.register(GroupAgentAssignment)
admin.site.register(Permission)
admin.site.register(UserPermission)
admin.site.register(ApplicationCPUIO)
admin.site.register(ApplicationMemoryIO)
admin.site.register(ApplicationDiskIO)
admin.site.register(Role)
admin.site.register(PermissionSet)

